version: '3.5'

services:

  geoserver:
    container_name: geoserver
    image: mborne/geoserver:2.21.1
    build:
      context: .
      args:
        version: '2.21.1'
    ports:
      - "8082:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.geoserver.rule=Host(`geoserver.${HOST_HOSTNAME}`)"
      #- "traefik.http.routers.geoserver.middlewares=cors@file"
    volumes:
      - geoserver-data:/var/geoserver-data-dir
    restart: unless-stopped

volumes:
  geoserver-data:
    name: geoserver-data

networks:
  geoserver:
